//
//  NotificationManager.swift
//  Octrum
//
//  Created by Marcelinus Gerardo on 30/10/25.
//

import Foundation
import UserNotifications
import UIKit
import Combine

class NotificationManager: NSObject, ObservableObject, UNUserNotificationCenterDelegate {
    static let shared = NotificationManager()
    
    // APNs device token (auto-generated by iOS)
    @Published var deviceToken: String?
    @Published var isAPNsRegistered: Bool = false
    
    private override init() {
        super.init()
        UNUserNotificationCenter.current().delegate = self
    }
    
    func requestAuthorization() {
        UNUserNotificationCenter.current().requestAuthorization(options: [.alert, .badge, .sound]) { granted, error in
            if granted {
                print("✅ Notification permission granted")
                
                DispatchQueue.main.async {
                    UIApplication.shared.registerForRemoteNotifications()
                }
            } else if let error = error {
                print("❌ Notification permission error: \(error.localizedDescription)")
            } else {
                print("⚠️ Notification permission denied")
            }
        }
    }
    
    func didRegisterForRemoteNotifications(withDeviceToken deviceToken: Data) {
        let tokenString = deviceToken.map { String(format: "%02.2hhx", $0) }.joined()
        
        DispatchQueue.main.async {
            self.deviceToken = tokenString
            self.isAPNsRegistered = true
        }
        
        print("✅ APNs Device Token: \(tokenString)")
        
        NotificationCenter.default.post(
            name: NSNotification.Name("APNsDeviceTokenReceived"),
            object: tokenString
        )
    }
    
    func didFailToRegisterForRemoteNotifications(withError error: Error) {
        print("❌ Failed to register for remote notifications: \(error.localizedDescription)")
        DispatchQueue.main.async {
            self.isAPNsRegistered = false
        }
    }
    
    func didReceiveRemoteNotification(_ userInfo: [AnyHashable: Any]) {
        print("📨 Received remote notification: \(userInfo)")
        
        if let aps = userInfo["aps"] as? [String: Any],
           let alert = aps["alert"] as? [String: Any],
           let title = alert["title"] as? String,
           let body = alert["body"] as? String {
            
            print("📱 APNs Alert - Title: \(title), Body: \(body)")
            
            // Check for media URL (rich notification)
            if let mediaUrl = userInfo["media-url"] as? String {
                print("🖼️ Rich notification with media: \(mediaUrl)")
            }
            
            // Check for custom alert data
            if let alertData = userInfo["alert_data"] as? [String: Any] {
                print("📋 Alert data: \(alertData)")
            }
            
            DispatchQueue.main.async {
                NotificationCenter.default.post(
                    name: NSNotification.Name("RefreshAlertList"),
                    object: nil
                )
            }
        }
    }
    
    // Notification while app is in FOREGROUND
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        completionHandler([.banner, .sound, .badge])
    }
    
    // User taps on the notification
    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
        print("📱 User tapped notification: \(response.notification.request.content.title)")
        completionHandler()
    }
    
    func sendNotification(title: String, body: String, badge: Int? = nil, soundName: String? = "alert.wav") {
        let content = UNMutableNotificationContent()
        content.title = title
        content.body = body
        
        if let soundName = soundName {
            content.sound = UNNotificationSound(named: UNNotificationSoundName(rawValue: soundName))
        } else {
            content.sound = .default
        }
        
        if let badge = badge {
            content.badge = NSNumber(value: badge)
        }
        
        let trigger = UNTimeIntervalNotificationTrigger(timeInterval: 0.1, repeats: false)
        let request = UNNotificationRequest(identifier: UUID().uuidString, content: content, trigger: trigger)
        
        UNUserNotificationCenter.current().add(request) { error in
            if let error = error {
                print("❌ Error sending notification: \(error.localizedDescription)")
            } else {
                print("✅ Notification sent: \(title)")
            }
        }
    }
    
    func incrementBadge() {
        UNUserNotificationCenter.current().getDeliveredNotifications { notifications in
            let newBadge = notifications.count + 1
            DispatchQueue.main.async {
                UIApplication.shared.applicationIconBadgeNumber = newBadge
            }
        }
    }
    
    func clearBadge() {
        DispatchQueue.main.async {
            UIApplication.shared.applicationIconBadgeNumber = 0
        }
    }
}
